vscode:
  extensions:
    - PKief.material-icon-theme@4.3.0:URe4ANXBLYHzB6CeGyTN8A==
    - eamodio.gitlens@10.2.1:WIWu3zHU4VPT8r/v866LUw==
    - dsznajder.es7-react-js-snippets@3.0.0:9YEGn/57fW8lJt7cVxJQDQ==
    - jpoissonnier.vscode-styled-components@0.0.31:UTVWjMEU7BgO0i65c1w35A==
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==